### ISSUE TITLE
Question: Should the instance of Client be shared / reused?

### ISSUE THREAD

**Issue by mozrat** [SOHU-Co/kafka-node#963] opened 2018-05-02 19:22 UTC
Hello,

Should instances of Client or Consumer be created as and when code needs to produce a message, or can they be more long-running. 

For example, created at application startup time and then shared amongst different code components?

**Comment by hyperlink** [comment] 2018-05-03 14:28
Clients can be long running but I would not recommend sharing client instances among different consumers/producers. And if possible handle kafka processing in a separate/child process.

**Comment by aikar** [comment] 2018-05-04 17:49
you absolutely can't share clients, as when you close a consumer, it will close the client too, and clients can't be reopened once closed.

so closing 1 consumer would break any other consumer sharing the client.

**Comment by anodynos** [comment] 2018-06-19 16:49
Is this [closing the client](https://github.com/SOHU-Co/kafka-node/blob/a3653ba2d75a180be1e35f25be66cae0c9dcaa1c/lib/consumer.js#L265) when we  `consumer.close()` the intended behaviour or is it a bug?

**Comment by hyperlink** [comment] 2018-06-21 17:46
@anodynos It's not a bug but it makes it unnecessarily complex for users to manage two resource-- which is why ConsumerGroup embeds the client inside of it.

**Closed** 2018-06-21 17:46 UTC
