### ISSUE TITLE
Negative messageSet key causes infinite loop when decoding

### ISSUE THREAD

**Issue by scooper91** [SOHU-Co/kafka-node#1120] opened 2018-11-06 11:25 UTC
* Node version: 8.10
* Kafka-node version: 3.0.1
* Kafka version: 1.1.1

We're often seeing data with a massive negative number as the `messageSet` key.

For example (logging `vars` in `.tap` [here](https://github.com/SOHU-Co/kafka-node/blob/218576755e453a243e509644215a911dd51543dc/lib/protocol/protocol.js#L285)):
```
{
  offset: 136315,
  messageSize: 257399,
  crc: 2,
  magicByte: 2,
  attributes: 11,
  timestamp: -2046469315732963300,
  key: -1912602623
}
```

This key is used to [slice the message set](https://github.com/SOHU-Co/kafka-node/blob/218576755e453a243e509644215a911dd51543dc/lib/protocol/protocol.js#L344) in `protocol.decodeMessageSet`.  As the key is negative, it is never slicing anything from `messageSet`, so the while loop condition (`while (messageSet.length > 0)`) is always true.

We're not setting this key anywhere (it is different to the message key, which we are setting) and I don't know why it is negative.  However, having a negative key should not cause an infinite loop.

Does anyone know:
 - What the the key in the message set is (the names of each field in a record set is different in the [Kafka docs](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-CommonRequestandResponseStructure))?
 - Why the key is used in the decoding of the message set?

If the key is required for decoding, a negative key should at least cause an error, rather than going round in an infinite loop.

Thanks! :)

**Comment by hyperlink** [comment] 2018-12-19 21:57
dupe of #1121

**Closed by hyperlink** 2018-12-19 21:57 UTC
