### ISSUE TITLE
TypeError: Cannot read property 'write' of undefined

### ISSUE THREAD

**Issue by ighack** [SOHU-Co/kafka-node#546] opened 2017-01-06 09:19 UTC
below is my code of Consumer 

```
var http = require('http');

http.createServer(function (request, response) {

    // 发送 HTTP 头部 
    // HTTP 状态值: 200 : OK
    // 内容类型: text/plain
    response.writeHead(200, {'Content-Type': 'text/plain'});

    var kafka = require('kafka-node'),
    Consumer = kafka.Consumer,
    //HighLevelConsumer = kafka.HighLevelConsumer,
    client = new kafka.Client(),
    consumer = new Consumer(
        client,
        payloads = [
            { topic:'fltest',partition:0},
            { topic:'fltest',partition:1},
            { topic:'fltest',partition:2}
        ],
        options = {
            groupId: 'kafka-node-group',
            autoCommit: false,
            fetchMaxWaitMs: 100,
            fetchMinBytes: 1,
            fetchMaxBytes: 1024 * 1024,
            fromOffset: false,
            encoding: 'utf8'
       }
    );
    //consumer = new HighLevelConsumer(
        //client,
        //[
            //{topic:'fltest'}
        //],
        //{
            //groupId: 'kafka-node-group',
            //autoCommit: false,
            //fetchMaxWaitMs: 100,
            //fetchMinBytes: 1,
            //fetchMaxBytes: 1024 * 1024,
            //fromOffset: false,
            //encoding: 'utf8'
        //}
    //);
    consumer.on('message', function (message) {
            console.log(message);
        });
    consumer.on('error', function (err) {
            //console.log(err);
        });
    //consumer.on('offsetOutOfRange', function (err) {
            //console.log(err);
        //});
    consumer.close(function(){});

    // 发送响应数据 "Hello World"
    response.end('Hello World\n');
}).listen(9999);

// 终端打印如下信息
console.log('Server running at http://127.0.0.1:9999/');

```

but it dosen't work

> E:\node_modules\.0.2.2@node-zookeeper-client\lib\ConnectionManager.js:624
>         if (!this.socket.write(packet.request.toBuffer())) {
>                         ^
> 
> TypeError: Cannot read property 'write' of undefined
>     at ConnectionManager.onPacketQueueReadable (E:\node_modules\.0.2.2@node-zook
> eeper-client\lib\ConnectionManager.js:624:25)
>     at emitNone (events.js:86:13)
>     at PacketQueue.emit (events.js:185:7)
>     at PacketQueue.push (E:\node_modules\.0.2.2@node-zookeeper-client\lib\Packet
> Queue.js:35:10)
>     at ConnectionManager.queue (E:\node_modules\.0.2.2@node-zookeeper-client\lib
> \ConnectionManager.js:711:30)
>     at ConnectionManager.close (E:\node_modules\.0.2.2@node-zookeeper-client\lib
> \ConnectionManager.js:248:10)
>     at Client.close (E:\node_modules\.0.2.2@node-zookeeper-client\index.js:229:2
> 8)
>     at Zookeeper.close (E:\node_modules\.1.0.7@kafka-node\lib\zookeeper.js:468:1
> 5)
>     at Client.close (E:\node_modules\.1.0.7@kafka-node\lib\client.js:163:11)
>     at Consumer.close (E:\node_modules\.1.0.7@kafka-node\lib\consumer.js:264:17)

**Comment by hyperlink** [comment] 2017-01-06 14:55
I think this might be caused by start your consumer and then closing it right away.

**Comment by ighack** [comment] 2017-01-09 02:23
I remove `consumer.close(function(){});`
it also dosen't work

> E:\node-kafka\Kafka-Node>node client.js
> Server running at http://127.0.0.1:9999/
> E:\node-kafka\Kafka-Node\node_modules\.1.1.0@kafka-node\lib\codec\snappy.js:9
>     throw new Error('Snappy codec is not installed');
>     ^
> 
> Error: Snappy codec is not installed
>     at Object.unavailableCodec (E:\node-kafka\Kafka-Node\node_modules\.1.1.0@kaf
> ka-node\lib\codec\snappy.js:9:11)
>     at Object.<anonymous> (E:\node-kafka\Kafka-Node\node_modules\.1.1.0@kafka-no
> de\lib\protocol\protocol.js:183:17)
>     at Object.self.tap (E:\node-kafka\Kafka-Node\node_modules\.0.3.0@binary\inde
> x.js:248:12)
>     at decodeMessageSet (E:\node-kafka\Kafka-Node\node_modules\.1.1.0@kafka-node
> \lib\protocol\protocol.js:161:8)
>     at Object.<anonymous> (E:\node-kafka\Kafka-Node\node_modules\.1.1.0@kafka-no
> de\lib\protocol\protocol.js:128:26)
>     at Object.self.tap (E:\node-kafka\Kafka-Node\node_modules\.0.3.0@binary\inde
> x.js:248:12)
>     at Object.decodePartitions (E:\node-kafka\Kafka-Node\node_modules\.1.1.0@kaf
> ka-node\lib\protocol\protocol.js:123:8)
>     at Object.self.loop (E:\node-kafka\Kafka-Node\node_modules\.0.3.0@binary\ind
> ex.js:267:16)
>     at Object.<anonymous> (E:\node-kafka\Kafka-Node\node_modules\.1.1.0@kafka-no
> de\lib\protocol\protocol.js:57:8)
>     at Object.self.loop (E:\node-kafka\Kafka-Node\node_modules\.0.3.0@binary\ind
> ex.js:267:16)
I am sure I have snappy

**Closed** 2017-01-19 19:55 UTC

**Comment by ltnilaysahu** [comment] 2018-03-06 07:15
Any solutions?. why was this issue closed.  I am also receiving this error "TypeError: Cannot read property 'write' of undefined" at ConnectionManager.onPacketQueueReadable

**Comment by rsryanstephen** [comment] 2018-06-14 12:52
Why was this issue closed? I am also receiving this error, no solution was posted

**Comment by hyperlink** [comment] 2018-06-21 16:40
@rsryanstephen I think it was closed because the last error appears to be missing snappy codec. Previous errors are related to using the deprecated Client which depended on zookeeper. KafkaClient should really be used instead.
