### ISSUE TITLE
Is ConsumerGroup commit automatically ?

### ISSUE THREAD

**Issue by serialLinker** [SOHU-Co/kafka-node#648] opened 2017-04-07 09:53 UTC
## Bug Report
I have a problem with the ConsumerGroup object. My protocol : 

- Get 3messages
- Don't commit them
- Kill the app
- Restart the app.

Because I've not commited message, when I restart the app I should get the 3 messages again, but I don't. Is the ConsumerGroup object is by default in autocommit mode ?

Thx.

### Environment

* Node version: 6.6.0
* Kafka-node version: 1.6.0
* Kafka version: 0.10

### For specific cases also provide
* Number of Brokers: 1
* Number partitions for topic: 1

### Include Sample Code to reproduce behavior

```js
self.options = {
    host: config['metadata.broker.list'], //zkhost
    autoCommit: false
    groupId: MY-GROUPID
    fetchMaxWaitMs: 1000,
    fetchMaxBytes: 1024 * 1024,
    fromOffset: 'earliest',
    connectOnReady: false,
    ssl : {
      rejectUnauthorized : "true",
      cert : fs.readFileSync(config['ssl.cert.path']+"/certs/kafka_client.pem", 'utf8'),
      key : fs.readFileSync(config['ssl.cert.path']+"/private/kafka_client.key", 'utf8'),
      ca : fs.readFileSync(config['ssl.cert.path']+"/certs/ca-cert", 'utf8'),
      passphrase : config['ssl.key.password']
    }
};

self.consumer = new ConsumerGroup(self.options, self.topics);

self.consumer.on('connect', function() {
  console.log('connect');
    debug("Consumer is ready");
})
.on('message', function(data) {
    debug("got message "+data);
});
```

**Comment by hyperlink** [comment] 2017-04-07 14:24
Yes, `autoCommit` is by default `true` but since you set it to `false` in your options It shouldn't be committing.

How is your consumer connecting if you have connectOnReady set to false? Are you calling `.connect` method somewhere else?

**Comment by serialLinker** [comment] 2017-04-07 14:29
@hyperlink , thx for your reply.

Yes I call the connect method next I've registered my "connect" and "message" handler.

**Comment by serialLinker** [comment] 2017-04-07 14:35
Is it possible that I have this problem because commits are save in kafka (in consumer_offsets) and kafka-node is connected with zookeeper ?

**Comment by hyperlink** [comment] 2017-04-07 15:55
`ConsumerGroup` only uses zookeeper for broker discovery and also migration from old zookeeper based HLC offsets if that option was turned on (off by default).

**Comment by michallevin** [comment] 2017-04-19 13:19
Is it possible to explicitly declare which offset the ConsumerGroup will read from regardless of its committed offset?

**Comment by hyperlink** [comment] 2017-04-19 14:29
@michallevin correct. `fromOffset` only applies when no offsets were committed previously. What's the use case for specifying a specific offset to read from?

**Comment by michallevin** [comment] 2017-04-19 15:49
@hyperlink Thanks for the clarification!

In most case, we use the last committed offset to read from topics, but when there are changes in logic we sometimes need to re-process the data from the beginning. We thought about committing all of the necessary topics to offset 0, and then reading as a solution to this. What do think think?

**Comment by hyperlink** [comment] 2017-04-20 13:34
For that case I recommend changing to a different groupId and then using `fromOffset` "earliest". Giving a specific offset could lead to an `InvalidConsumerOffsetError` if those offsets are out of retention.

**Comment by lazylad91** [comment] 2017-04-23 05:00
@hyperlink  I am commiting my messages by using sendOffsetCommitRequest function. But when i restart my consumer. I get last committed message again. Do you have any idea how to resolve this?

**Comment by michallevin** [comment] 2017-04-23 16:27
@hyperlink Regarding `fromOffset` that we discussed earlier...

I am manually committing my messages using `offset.commit`, and expect the ConsumerGroup to start from the last committed offset each time I run the program.
I log the latest committed offset using `offset.fetchCommits`, which looks correct (the last offset when I last stopped the program), but the consumer does not begin to read from this offset (and the commit callback is never called). Furthermore, its behavior changes depending on the value of `fromOffset`, which should not matter since I have a committed offset ('none' returns `[Error: kafka-node-client owns topics and partitions which contains no saved offsets for group 'Test'], and there is only 1 partition`).

**How can it be that `offset.fetchCommits` returns the correct commit, but that the ConsumerGroup behaves as if there is no committed offset?**

```
const kafka = require('kafka-node');
const sleep = require('sleep');

const options = {
  groupId: 'Test',
  autoCommit: false,
  host: '127.0.0.1:2181',
  sessionTimeout: 15000,
  protocol: ['roundrobin'],
  fromOffset: 'none'
};

const client = new kafka.Client();
const offset = new kafka.Offset(client);

const ConsumerGroup = kafka.ConsumerGroup;
const consumerGroup1 = new ConsumerGroup(options, ['fake-topic']);


offset.fetchCommits('Test', [{ topic: 'fake-topic', partition: 0 }], (error, offsets) => { console.log(offsets) })

consumerGroup1.on('message', (message) => {
  console.log(`topic ${message.topic} partition ${message.partition} offset ${message.offset}`);
  offset.commit('Test', [{
                                        topic: message.topic,
                                        partition: message.partition, //default 0
                                        offset: message.offset,
                                        metadata: 'm', //default 'm'
                                     }], (err, data) => {
                                     console.log("successfully committed");
                                     console.log("err:" + err);
                                     console.log("data: " + data);
                                     });
  sleep.sleep(1);
});

consumerGroup1.on('error', (error) => {
  console.log(error);
});
```

**Comment by hyperlink** [comment] 2017-04-23 22:38
The `ConsumerGroup` has state on what offsets it's supposed to have. If you commit a different offset than what it expects it could be overwritten next time `autoCommit/commit` is called.

**Comment by michallevin** [comment] 2017-04-24 11:18
@hyperlink My question is - shouldn't the offset returned by offset.fetchCommits be the same as the offset that the ConsumerGroup uses (according to testing it is not)?

Also, running 2 process that each have a consumerGroup with the same group-id read from the same topic and commit each message manually using sendOffsetCommitRequest results in **both consumers reading all messages. Is this a bug or expected behavior?**

**Comment by lazylad91** [comment] 2017-04-26 01:25
@hyperlink Can you please elaborate on it, as i dont want to process the message again if its commited.
How to prevent consumergroup to get the last uncommited message?

**Comment by hyperlink** [comment] 2017-04-26 13:59
> How to prevent consumergroup to get the uncommited message only if its there?

Not sure what that means but committing manually is tricky to get right.

**Comment by lazylad91** [comment] 2017-04-26 23:43
I meant, that right now, if i start my consumer i get the last committed message.
I dont want that. I only want messages which are not committed. And if there is 0 uncommitted message in topic. I dont want my consumer to consume anything, till a new message is added in the topic.

**Comment by michallevin** [comment] 2017-04-27 07:49
Would it be correct to manually commit offset+1 ?

**Closed** 2017-05-11 15:53 UTC
