### ISSUE TITLE
Messages delivered repeatedly

### ISSUE THREAD

**Issue by kryptx** [SOHU-Co/kafka-node#955] opened 2018-04-26 23:27 UTC
When we deployed a service depending on version 2.6.0, we noticed we were receiving messages many times. In the worst cases, thousands of times across our consumer group. These deliveries often happen (on one host) many times **even within the same millisecond**. They have the same topic, same partition, same offset, and same payload.

Number of brokers, number of partitions seems irrelevant. Reverting to kafka-node 2.3.0 alleviated the issue.

I don't have debug output or repro steps, but I can probably get them if you can't think of any way this might happen.

### Environment

* Node version: 6.13.1
* Kafka-node version: 2.6.0
* Kafka version: 0.9.0

**Comment by ufmemo** [comment] 2018-04-26 23:43
Same here... spent two days looking at this issue... fixed by reverting to 2.5.0.

**Comment by kunle-e** [comment] 2018-04-26 23:50
I've struggled with this for many hours. Went back to an older version and the problem went away.

**Comment by anajavi** [comment] 2018-04-27 12:40
Same thing.

Environment:
- Node version: 8.11.1
- Kafka-node version: 2.6.0
- Kafka version: 1.0.1

**Comment by hyperlink** [comment] 2018-04-27 14:51
Looks like this is caused by V2 fetch changes. The issue reveals itself when connecting to multiple brokers and unfortunately our tests only connects to one broker.

I'm reverting that commit and publish it as patch release shortly.

**Comment by ph1l337** [comment] 2018-04-27 15:10
+1

**Comment by enjine** [comment] 2018-04-27 18:03
confirmed. locking to version 2.5.0 restores expected behavior. When can we expect the patch to be available?

**Comment by hyperlink** [comment] 2018-04-27 18:08
It's published as 2.6.1.

**Comment by anajavi** [comment] 2018-04-27 18:14
2.6.1 works for me

**Comment by hyperlink** [comment] 2018-04-27 18:59
@enjine @ph1l337 @kunle-e @ufmemo @kryptx have 2.6.1 resolve the issue?

**Closed** 2018-04-29 15:27 UTC
Labels: bug
