### ISSUE TITLE
When broker dies Producer dies too

### ISSUE THREAD

**Issue by inteloid** [SOHU-Co/kafka-node#200] opened 2015-04-24 11:53 UTC
Hi guys.

When one of my kafka brokers die, my producer (it's always at a high load) also dies.

**Comment by haio** [comment] 2015-04-28 13:01
Hi, to prevent program crashing, producer should always listen `error` event.

**Comment by wsimmonds** [comment] 2015-05-06 15:02
@haio: Is this a deliberate design for Kafka-node? As it deviates from the official Java version - where I'd expect in the event of an error for the producer to retry/refresh metadata.

Any feedback would be welcome - as we evaluated Kafka-node and found this an issue too.

"The intended behavior is that the client will periodically attempt to reconnect and update metadata until either it can reconnect or it discovers that a new node has taken over leadership for the given partition."

Source: Jay Kreps https://issues.apache.org/jira/browse/KAFKA-1642

**Comment by hyperlink** [comment] 2016-04-02 14:29
Should be fixed in #281

**Closed by hyperlink** 2016-04-02 14:29 UTC
