### ISSUE TITLE
why HighLevelProducer  cannot round robin?

### ISSUE THREAD

**Issue by jaybill-lee** [SOHU-Co/kafka-node#1104] opened 2018-10-22 03:27 UTC
## Questions

I have a kafka broker, and it has 5 partitions.   When I use the HighLevelProducer to send data to the broker,  it just send to partion 0. My code shows below. 

```
var host = '192.168.153.130:9092';
var kafka = require('kafka-node'),
  HighLevelProducer = kafka.HighLevelProducer,
  client = new kafka.KafkaClient({kafkaHost: host}),
  producer = new HighLevelProducer(client),
  payloads = [
        { topic: 'topic1', messages:'hello world' },
  ];
producer.on('ready', function() {
  setInterval(() => {
    client.refreshMetadata(['topic1'], function() {
      producer.send(payloads, function(err, data) {
        console.log(data);
      });
    });
  }, 2000);
});

```

**Comment by hyperlink** [comment] 2018-10-22 18:29
I'm closing this since it's a dupe of #1103

**Closed by hyperlink** 2018-10-22 18:29 UTC
