### ISSUE TITLE
No timestamps in consumed messages

### ISSUE THREAD

**Issue by weekens** [SOHU-Co/kafka-node#812] opened 2017-11-24 12:30 UTC
## Bug Report

When I receive messages with `ConsumerGroup`, the messages do not contain Kafka timestamps.

### Environment

* Node version: 8.9.1
* Kafka-node version: 2.3.0
* Kafka version: 0.11.0.1

### Include Sample Code to reproduce behavior

```js
var kafka = require('kafka-node');

var consumer = new kafka.ConsumerGroup(
  {
    kafkaHost: 'localhost:9092',
    groupId: 'test-node'
  },
  'TEST');

consumer.connect();

consumer.on('message', msg => {
  console.log(JSON.stringify(msg, null, 2));
});

consumer.on('error', err => {
  console.error('Error: ' + err);
});
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

After sending test message with:

```
$ kafka-console-producer --broker-list localhost:9092 --topic TEST
> Hello 3
```

I get:

```
/usr/bin/node /home/weekens/workspace/saymon/backend/server/worksheet.js
  kafka-node:KafkaClient Connect attempt 1 +0ms
  kafka-node:KafkaClient Trying to connect to host: localhost port: 9092 +4ms
  kafka-node:ConsumerGroup Connecting kafka-node-client +7ms
  kafka-node:KafkaClient Sending versions request to localhost:9092 +6ms
  kafka-node:KafkaClient broker socket connected {"host":"localhost","port":"9092"} +1ms
  kafka-node:ConsumerGroup GroupCoordinator Response: { coordinatorHost: 'weekens-laptop',
  coordinatorPort: 9092,
  coordinatorId: 0 } +8ms
  kafka-node:KafkaClient found 1 connected broker(s) +3ms
  kafka-node:ConsumerGroupRecovery tryToRecoverFrom connect { BrokerNotAvailableError: Broker not available
    at new BrokerNotAvailableError (/home/weekens/workspace/saymon/backend/server/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at KafkaClient.Client.sendGroupRequest (/home/weekens/workspace/saymon/backend/server/node_modules/kafka-node/lib/client.js:296:15)
    at KafkaClient.Client.sendJoinGroupRequest (/home/weekens/workspace/saymon/backend/server/node_modules/kafka-node/lib/client.js:308:8)
    at /home/weekens/workspace/saymon/backend/server/node_modules/kafka-node/lib/consumerGroup.js:453:21
    at nextTask (/home/weekens/workspace/saymon/backend/server/node_modules/kafka-node/node_modules/async/dist/async.js:5310:14)
    at next (/home/weekens/workspace/saymon/backend/server/node_modules/kafka-node/node_modules/async/dist/async.js:5317:9)
    at /home/weekens/workspace/saymon/backend/server/node_modules/kafka-node/node_modules/async/dist/async.js:958:16
    at KafkaClient.wrappedFn (/home/weekens/workspace/saymon/backend/server/node_modules/kafka-node/lib/kafkaClient.js:375:14)
    at KafkaClient.Client.handleReceivedData (/home/weekens/workspace/saymon/backend/server/node_modules/kafka-node/lib/client.js:764:60)
    at Socket.<anonymous> (/home/weekens/workspace/saymon/backend/server/node_modules/kafka-node/lib/kafkaClient.js:598:10) message: 'Broker not available' } +1ms
  kafka-node:ConsumerGroupRecovery RECOVERY from connect: kafka-node-client retrying in 1000 ms { BrokerNotAvailableError: Broker not available
    at new BrokerNotAvailableError (/home/weekens/workspace/saymon/backend/server/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at KafkaClient.Client.sendGroupRequest (/home/weekens/workspace/saymon/backend/server/node_modules/kafka-node/lib/client.js:296:15)
    at KafkaClient.Client.sendJoinGroupRequest (/home/weekens/workspace/saymon/backend/server/node_modules/kafka-node/lib/client.js:308:8)
    at /home/weekens/workspace/saymon/backend/server/node_modules/kafka-node/lib/consumerGroup.js:453:21
    at nextTask (/home/weekens/workspace/saymon/backend/server/node_modules/kafka-node/node_modules/async/dist/async.js:5310:14)
    at next (/home/weekens/workspace/saymon/backend/server/node_modules/kafka-node/node_modules/async/dist/async.js:5317:9)
    at /home/weekens/workspace/saymon/backend/server/node_modules/kafka-node/node_modules/async/dist/async.js:958:16
    at KafkaClient.wrappedFn (/home/weekens/workspace/saymon/backend/server/node_modules/kafka-node/lib/kafkaClient.js:375:14)
    at KafkaClient.Client.handleReceivedData (/home/weekens/workspace/saymon/backend/server/node_modules/kafka-node/lib/client.js:764:60)
    at Socket.<anonymous> (/home/weekens/workspace/saymon/backend/server/node_modules/kafka-node/lib/kafkaClient.js:598:10) message: 'Broker not available' } +2ms
  kafka-node:KafkaClient Received versions response from localhost:9092 +3ms
  kafka-node:KafkaClient setting api support to {"21":{"min":0,"max":0,"usable":false},"22":{"min":0,"max":0,"usable":false},"23":{"min":0,"max":0,"usable":false},"24":{"min":0,"max":0,"usable":false},"25":{"min":0,"max":0,"usable":false},"26":{"min":0,"max":0,"usable":false},"27":{"min":0,"max":0,"usable":false},"28":{"min":0,"max":0,"usable":false},"29":{"min":0,"max":0,"usable":false},"30":{"min":0,"max":0,"usable":false},"31":{"min":0,"max":0,"usable":false},"32":{"min":0,"max":0,"usable":false},"33":{"min":0,"max":0,"usable":false},"produce":{"min":0,"max":3,"usable":2},"fetch":{"min":0,"max":5,"usable":0},"offset":{"min":0,"max":2,"usable":0},"metadata":{"min":0,"max":4,"usable":0},"leader":{"min":0,"max":0,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":3,"usable":false},"controlledShutdown":{"min":1,"max":1,"usable":false},"offsetCommit":{"min":0,"max":3,"usable":2},"offsetFetch":{"min":0,"max":3,"usable":1},"groupCoordinator":{"min":0,"max":1,"usable":0},"joinGroup":{"min":0,"max":2,"usable":0},"heartbeat":{"min":0,"max":1,"usable":0},"leaveGroup":{"min":0,"max":1,"usable":0},"syncGroup":{"min":0,"max":1,"usable":0},"describeGroups":{"min":0,"max":1,"usable":0},"listGroups":{"min":0,"max":1,"usable":0},"saslHandshake":{"min":0,"max":0,"usable":false},"apiVersions":{"min":0,"max":1,"usable":0},"createTopics":{"min":0,"max":2,"usable":false},"deleteTopics":{"min":0,"max":1,"usable":false}} +0ms
  kafka-node:KafkaClient updating metadatas +27ms
  kafka-node:ConsumerGroup Connecting kafka-node-client +0ms
  kafka-node:KafkaClient updating metadatas +26ms
  kafka-node:ConsumerGroup GroupCoordinator Response: { coordinatorHost: 'weekens-laptop',
  coordinatorPort: 9092,
  coordinatorId: 0 } +3ms
  kafka-node:KafkaClient clearing localhost:9092 callback queue without error +3ms
  kafka-node:KafkaClient Sending versions request to weekens-laptop:9092 +0ms
  kafka-node:KafkaClient getApiVersions request timedout probably less than 0.10 using base support +501ms
  kafka-node:KafkaClient setting api support to {"produce":{"min":0,"max":1,"usable":1},"fetch":{"min":0,"max":0,"usable":0},"offset":{"min":0,"max":0,"usable":0},"metadata":{"min":0,"max":0,"usable":0},"leader":null,"stopReplica":null,"updateMetadata":null,"controlledShutdown":null,"offsetCommit":{"min":0,"max":2,"usable":2},"offsetFetch":{"min":0,"max":1,"usable":1},"groupCoordinator":{"min":0,"max":0,"usable":0},"joinGroup":{"min":0,"max":0,"usable":0},"heartbeat":{"min":0,"max":0,"usable":0},"leaveGroup":{"min":0,"max":0,"usable":0},"syncGroup":{"min":0,"max":0,"usable":0},"describeGroups":{"min":0,"max":0,"usable":0},"listGroups":{"min":0,"max":0,"usable":0},"saslHandshake":null,"apiVersions":{"min":0,"max":0,"usable":0},"createTopics":null,"deleteTopics":null} +0ms
  kafka-node:ConsumerGroup Connect ignored. Currently connecting. +439ms
  kafka-node:ConsumerGroup joinGroupResponse {"members":[{"subscription":["TEST"],"version":0,"id":"kafka-node-client-9371f463-7bf5-4d56-8620-a5359dc90a2a"}],"generationId":6,"groupProtocol":"roundrobin","leaderId":"kafka-node-client-9371f463-7bf5-4d56-8620-a5359dc90a2a","memberId":"kafka-node-client-9371f463-7bf5-4d56-8620-a5359dc90a2a"} from kafka-node-client +5s
  kafka-node:ConsumerGroup Assigning Partitions to members [ { subscription: [ 'TEST' ],
    version: 0,
    userData: undefined,
    id: 'kafka-node-client-9371f463-7bf5-4d56-8620-a5359dc90a2a' } ] +0ms
  kafka-node:ConsumerGroup Using group protocol roundrobin +1ms
  kafka-node:ConsumerGroup loadingMetadata for topics: [ 'TEST' ] +3ms
  kafka-node:ConsumerGroup mapTopicToPartitions { TEST: [ '0' ] } +3ms
  kafka-node:Roundrobin topicPartition: {"TEST":["0"]} +1ms
  kafka-node:Roundrobin groupMembers: [{"subscription":["TEST"],"version":0,"id":"kafka-node-client-9371f463-7bf5-4d56-8620-a5359dc90a2a"}] +0ms
  kafka-node:Roundrobin members [ 'kafka-node-client-9371f463-7bf5-4d56-8620-a5359dc90a2a' ] +0ms
  kafka-node:Roundrobin subscribers { 'kafka-node-client-9371f463-7bf5-4d56-8620-a5359dc90a2a': [ 'TEST' ] } +1ms
  kafka-node:Roundrobin round robin on topic partition pairs:  [ { topic: 'TEST', partition: '0' } ] +0ms
  kafka-node:ConsumerGroup SyncGroup Request from kafka-node-client-9371f463-7bf5-4d56-8620-a5359dc90a2a +1ms
  kafka-node:ConsumerGroup SyncGroup Response +3ms
  kafka-node:ConsumerGroup kafka-node-client owns topics:  { TEST: [ 0 ] } +0ms
  kafka-node:ConsumerGroup kafka-node-client fetchOffset Response: {"TEST":{"0":2}} +3ms
  kafka-node:ConsumerGroup Has saved offsets +0ms
  kafka-node:ConsumerGroup generationId 6 +1ms
  kafka-node:ConsumerGroup startFetch is true +0ms
  kafka-node:ConsumerGroup kafka-node-client started heartbeats at every 10000 ms +3ms
{
  "topic": "TEST",
  "value": "Hello 3",
  "offset": 2,
  "partition": 0,
  "highWaterOffset": 3,
  "key": null
}
```

**Comment by hyperlink** [comment] 2018-02-14 14:14
Looks like we need to support up to V2 of the fetch request/response before we are able to read the timestamp.

**Comment by vamshireddy21** [comment] 2018-02-22 21:35
Any fix for this issue.

**Comment by hyperlink** [comment] 2018-02-22 21:57
There is a fix in the works.

**Comment by vamshireddy21** [comment] 2018-03-12 15:36
I am using a java client. I am still having the same issue

**Comment by vamshireddy21** [comment] 2018-03-12 17:42
Whats is the fix. I just want to know what is the fix in the java client

**Comment by hyperlink** [comment] 2018-03-12 18:36
@vamshireddy21 there's some issues with the fix in the consumer side. Not sure how this relates to your java producer problem.

**Comment by vamshireddy21** [comment] 2018-03-12 21:07
Let me tell you my scenario. I am producing some messages to a kafka topic using new Java API. The produced messages are taking timestamp as negative.(Checked using kafka-console-consumer) Using Kafka Streams API i want to consume those messages and do some transformations and post it to an another kafka topic.  So as part of kafka streams job, it needs to consume the data first. During consuming, my kafka streams application is throwing me an error stating 


Exception in thread "StreamThread-1" org.apache.kafka.streams.errors.StreamsException: Input record ConsumerRecord(topic = XXXX, partition = 0, offset = 0, CreateTime = -1, checksum = 2486091252, serialized key size = -1, serialized value size = 126, key = null, has invalid (negative) timestamp. Possibly because a pre-0.10 producer client was used to write this record to Kafka without embedding a timestamp, or because the input topic was created before upgrading the Kafka cluster to 0.10+. Use a different TimestampExtractor to process this data.
	at org.apache.kafka.streams.processor.FailOnInvalidTimestamp.onInvalidTimestamp(FailOnInvalidTimestamp.java:62)
	at org.apache.kafka.streams.processor.ExtractRecordMetadataTimestamp.extract(ExtractRecordMetadataTimestamp.java:60)
	at org.apache.kafka.streams.processor.FailOnInvalidTimestamp.extract(FailOnInvalidTimestamp.java:46)
	at org.apache.kafka.streams.processor.internals.RecordQueue.addRawRecords(RecordQueue.java:86)
	at org.apache.kafka.streams.processor.internals.PartitionGroup.addRawRecords(PartitionGroup.java:117)
	at org.apache.kafka.streams.processor.internals.StreamTask.addRecords(StreamTask.java:158)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:619)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:368)


Where as if i try to produce the data using kafka-console-producer its working fine.


I am using Kafka Clients 1.0.0 API. And my kafka brokers are all above 0.10+.

Can you help me over this issue.

**Comment by natemccallum** [comment] 2018-03-13 18:25
I am having the exact same issue @vamshireddy21 is having. Streams API job throwing the exception because timestamp is negative. In fact I am running the Kafka Tool 2.0.1 and see blank timestamps for the messages, as if the producer isn't even setting one or pulling the one set in the event.

<img width="1295" alt="screen shot 2018-03-13 at 2 24 30 pm" src="https://user-images.githubusercontent.com/6003924/37361891-5154d6e4-26ca-11e8-9c66-369b6d6d0fe9.png">

**Comment by hyperlink** [comment] 2018-03-16 15:55
@vamshireddy21 you're using kafka java API to produce the message and then using Kafka Streams to consume it. Can you explain how kafka-node fits into your flow?

**Comment by natemccallum** [comment] 2018-03-21 13:12
My client is nodejs and I'm using kafka-node and I'm not getting timestamps. Using a different lang I had the same issue and found there was a setting to identify the version of the broker. Once I set that to a value greater that kafka 0.10.0 I started to see timestamps. Is there a setting that can be set in kafka-node to achieve the same?

**Closed** 2018-04-12 13:57 UTC
Labels: enhancement, protocol

**Comment by vamshireddy21** [comment] 2018-06-20 16:53
Setting the message.timestamp.type on topic level worked in my scenario.

By default message.timestamp.type=CreateTime, this means that a timestamp must be added by the producer. However if a timestamp is not added then the exception occurs in Streams Application:

As we are using a third party producer so we need to set message.timestamp.type=LogAppendTime.
By setting it to LogAppendTime, a timestamp on each message is added when it is received by the broker.

When a leader broker receives a message

If message.timestamp.type=LogAppendTime, the server will override the timestamp with its current local time and append the message to the log.
If the message is a compressed message. the timestamp in the wrapper message will be updated to current server time. Broker will set the timestamp type bit in wrapper messages to 1. Broker will ignore the inner message timestamp. We do this instead of writing current server time to each message is to avoid recompression penalty when people are using LogAppendTime.
If the message is a non-compressed message, the timestamp in the message will be overwritten to current server time.
If message.timestamp.type=CreateTime
If the time difference is within a configurable threshold max.message.time.difference.ms, the server will accept it and append it to the log. For compressed message, server will update the timestamp in compressed message to the largest timestamp of the inner messages.
If the time difference is beyond the configured threshold max.message.time.difference.ms, the server will reject the entire batch with TimestampExceededThresholdException.
message.timestamp.type and max.message.time.difference.ms will be a per topic configuration.

**Comment by cravi24** [comment] 2019-07-29 06:56
For me, i was getting this same issue even for kafka client version>2.0. Root cause for me was a very low timeout of 500ms for connecting to kafka client which would make producer request to use default settings for kafka version 0.9. Increasing this timeout fixed the issue for me.
```
const client = new KafkaNode.KafkaClient({
      kafkaHost: config.bootstrap_servers,
      versions: {
        requestTimeout: 10000,
      }
});
```
